sudo: true
services:
    - docker

before_install:
    - docker info
    - docker version

    - docker build  -f test/Dockerfile-ubuntu14.04      -t nomad_exporter_trusty       .
    - docker build  -f test/Dockerfile-ubuntu12.04      -t nomad_exporter_precise      .
    - docker build  -f test/Dockerfile-debian8          -t nomad_exporter_jessie       .
    - docker build  -f test/Dockerfile-debian7          -t nomad_exporter_wheezy       .
    - docker build  -f test/Dockerfile-centos7          -t nomad_exporter_centos7      .
    - docker build  -f test/Dockerfile-centos6          -t nomad_exporter_centos6      .
    - docker build  -f test/Dockerfile-ubuntu14.04-git  -t nomad_exporter_trusty_git   .
    - docker build  -f test/Dockerfile-debian8-git      -t nomad_exporter_jessie_git   .
    - docker build  -f test/Dockerfile-centos7-git      -t nomad_exporter_centos7_git  .

script:
    - docker run  -v $(pwd):/data  nomad_exporter_trusty
    - docker run  -v $(pwd):/data  nomad_exporter_precise
    - docker run  -v $(pwd):/data  nomad_exporter_jessie
    - docker run  -v $(pwd):/data  nomad_exporter_wheezy
    - docker run  -v $(pwd):/data  nomad_exporter_centos7
    - docker run  -v $(pwd):/data  nomad_exporter_centos6
    - docker run  -v $(pwd):/data  nomad_exporter_trusty_git
    - docker run  -v $(pwd):/data  nomad_exporter_jessie_git
    - docker run  -v $(pwd):/data  nomad_exporter_centos7_git

    - echo "==> Validating the test results..."
    - grep '^nomad_up' result-ubuntu14.04
    - grep '^nomad_up' result-ubuntu12.04
    - grep '^nomad_up' result-centos7
    - grep '^nomad_up' result-centos6
    - grep '^nomad_up' result-debian8
    - grep '^nomad_up' result-debian7
    - grep '^nomad_up' result-ubuntu14.04-git
    - grep '^nomad_up' result-centos7-git
    - grep '^nomad_up' result-debian8-git

notifications:
    webhooks: https://galaxy.ansible.com/api/v1/notifications/
